---
title: "마르시아의 사례"
---


하지만 모든 사례가 캐시 같지는 않다. 다른 많은 패턴이 있으며, 일부는 꽤 흔하다. 마르시아는 내 장기 치료 사례 중 아주 초기 케이스였다. 그녀는 20대 중반의 꽤 부유한 젊은 여성으로, 전반적인 무쾌감증(anhedonia) 때문에 내게 왔다. 그녀는 자기 존재의 잘못된 점을 딱 꼬집어 말할 수는 없었지만, 설명할 수 없을 만큼 기쁨이 없다고 느꼈다. 확실히 그녀는 기쁨이 없어 보였다. 부유함과 대학 교육에도 불구하고 그녀는 빈곤하고 지저분하고 늙은 이민자 여성처럼 보였다. 치료 첫해 내내 그녀는 파란색, 회색, 검은색 또는 갈색의 잘 맞지 않는 옷을 변함없이 입고 다녔고, 비슷한 색조의 거대하고 더럽고 해어진 여행가방을 들고 다녔다. 그녀는 지적인 부모의 외동딸이었는데, 둘 다 매우 성공적인 대학 교수였고, 종종 종교를 "나중에 하늘에서 받는 파이"라고 믿는 종류의 사회주의자들이었다. 그들은 그녀가 어린 청소년기에 친구와 교회에 다녔을 때 그녀를 놀렸다.

치료를 시작할 무렵 마르시아는 부모에게 전적으로 동의했다. 맨 처음 그녀는 다소 자랑스럽고 거칠게 자신이 무신론자라고 선언했다—우유부단한 무신론자가 아니라, 인류가 신이 존재하거나 존재할지 모른다는 망상에서 벗어날 수 있다면 훨씬 더 나아질 것이라고 믿는 진짜 무신론자라고 했다. 흥미롭게도 마르시아의 꿈은 종교적 상징으로 가득 차 있었는데, 방으로 날아드는 새들이 부리에 고대 언어로 모호한 메시지가 쓰인 두루마리를 물고 있는 식이었다.

하지만 나는 그녀 무의식의 이런 측면으로 마르시아를 직면시키지 않았다. 실제로 우리는 2년의 치료 과정 내내 종교 문제를 전혀 다루지 않았다. 우리가 주로 아주 길게 초점을 맞춘 것은 그녀와 부모의 관계였다. 두 사람은 경제적으로는 그녀에게 잘해주었지만 지적으로 엄격한 방식으로 정서적으로는 유별나게 거리가 먼, 가장 지적이고 합리적인 개인들이었다. 정서적 거리 외에도 그들 둘 다 자신의 커리어에 매우 많이 투자했기 때문에 그녀를 위한 시간이나 에너지가 거의 없었다. 그 결과 마르시아는 편안하고 온전한 가정을 가졌음에도 불구하고 소위 "불쌍한 부자 소녀", 심리적 고아였다. 하지만 그녀는 이것을 보기를 꺼려했다. 그녀는 부모가 자신을 상당히 박탈했다고 내가 제안했을 때 분개했고, 내가 그녀가 고아처럼 입고 다닌다고 지적했을 때 분개했다. 그건 단지 새로운 스타일일 뿐이고 내가 비판할 권리는 없다고 그녀는 말했다.

마르시아와의 치료 진전은 고통스러울 정도로 점진적이었지만 극적이었다. 핵심 요소는 우리가 서로 천천히 구축할 수 있었던 관계의 따뜻함과 친밀함이었는데, 이는 그녀가 부모와 가졌던 관계와 대조되었다. 치료 2년 차가 시작될 무렵 어느 아침 마르시아는 새 가방을 들고 세션에 들어왔다. 그것은 그녀의 낡은 여행가방 크기의 3분의 1밖에 되지 않았고 밝은 색상들의 향연이었다. 그 후 대략 한 달에 한 번씩 그녀는 밝은 오렌지색, 노란색, 연한 파란색과 초록색의 새 색상을 옷장에 추가했는데, 마치 꽃이 천천히 꽃잎을 펼치는 것 같았다. 나와의 마지막에서 두 번째 세션에서 그녀는 자신이 얼마나 기분 좋은지에 대해 생각하다가 말했다. "있잖아요, 이상하지만, 내 안만 변한 게 아니에요. 내 밖의 모든 것도 변한 것 같아요. 여전히 여기 있고, 똑같은 낡은 집에서 살고, 똑같은 낡은 일들을 좀 하고 있지만, 세상 전체가 아주 달라 보이고, 아주 다르게 느껴져요. 따뜻하고 안전하고 사랑스럽고 흥미진진하고 좋은 느낌이에요. 제가 무신론자라고 말했던 거 기억해요. 더 이상 그런지 확신할 수 없어요. 사실 그런 것 같지 않아요. 가끔 지금 세상이 옳게 느껴질 때, 나는 혼잣말을 해요."

"'있잖아, 정말 신이 있을 거라 장담해. 신 없이는 세상이 이렇게 옳을 수가 없을 거야.' 웃기죠. 이런 종류의 일에 대해 어떻게 말해야 할지 모르겠어요. 그냥 연결된 느낌, 진짜인 느낌, 내가 아주 큰 그림의 진짜 일부인 것 같은 느낌이 들어요. 그 그림을 많이 볼 수는 없지만, 그게 거기 있다는 걸 알고, 그게 선하다는 걸 알고, 내가 그 일부라는 걸 알아요."

치료를 통해 캐시는 신이라는 개념이 모든 중요한 것이었던 곳에서 아무 중요성도 없는 곳으로 이동했다. 반면 마르시아는 신이라는 개념을 거부하던 위치에서 그것이 자신에게 꽤 의미 있어지는 위치로 이동했다. 같은 과정, 같은 치료사였지만 겉보기에 반대되는 결과가 나왔고 둘 다 성공적이었다. 이것을 어떻게 설명해야 할까? 그렇게 하려 시도하기 전에 또 다른 유형의 사례를 고려해 보자. 캐시의 사례에서는 치료사가 그녀의 종교적 아이디어에 적극적으로 도전하여 그녀 삶에서 신 개념의 영향력을 극적으로 감소시키는 방향으로 변화를 가져와야 했다. 마르시아의 경우 치료사가 어떤 식으로든 그녀의 종교적 개념에 도전하지 않았음에도 신의 개념이 증가된 영향력을 갖기 시작했다. 치료사가 환자의 무신론이나 불가지론에 적극적으로 도전하고 의도적으로 환자를 종교성(religiosity)의 방향으로 이끄는 것이 필요한 경우가 있을까?
