---
title: "악의 문제"
---


게으름이 원죄이고 병든 자아 형태의 게으름이 악마일 수도 있다고 제안했으니, 악의 본질에 대해 몇 가지 언급을 함으로써 그림을 완성하는 것이 적절하다. 악의 문제는 아마도 모든 신학적 문제 중 가장 큰 문제일 것이다. 그러나 꽤 많은 다른 "종교적" 이슈들과 마찬가지로, 심리학이라는 과학은 몇 가지 사소한 예외를 제외하고 악이 존재하지 않는 것처럼 행동해 왔다. 그러나 잠재적으로 심리학은 이 주제에 기여할 바가 많다. 나는 나중에 좀 더 긴 저작에서 그런 기여의 일부를 할 수 있기를 바란다. 당장은 이 책의 주제에 주변적일 뿐이므로, 악의 본질에 대해 도달한 네 가지 결론을 간략히 진술하는 것으로 제한하겠다.

첫째, 나는 악이 실재한다는 결론에 도달했다. 그것은 미지의 것을 설명하려 힘없이 시도하는 원시적 종교 마음의 상상력의 산물이 아니다. 선(goodness) 앞에서 증오로 반응하며 자신들의 힘이 닿는 한 선을 파괴하려는 사람들, 그리고 사람들로 구성된 제도들이 정말로 있다. 그들은 의식적인 악의를 가지고 그렇게 하는 것이 아니라, 맹목적으로, 자신의 악을 자각하지 못한 채—참으로, 그런 자각을 피하려 애쓰며—그렇게 한다. 종교 문헌에서 악마에 대해 묘사되듯이, 그들은 빛을 미워하고 본능적으로 빛을 피하기 위해 무엇이든 하며, 빛을 끄려 시도하는 것도 포함한다. 그들은 자신의 자녀들과 자신들의 권력하에 있는 다른 모든 존재 안의 빛을 파괴할 것이다.

악한 사람들은 빛을 미워하는데, 빛이 그들 자신을 스스로에게 드러내기 때문이다. 그들은 선함을 미워하는데 그것이 자신들의 나쁨을 드러내기 때문이다. 그들은 사랑을 미워하는데 그것이 자신들의 게으름을 드러내기 때문이다. 그들은 그런 자기 자각의 고통을 피하기 위해 빛, 선함, 사랑을 파괴할 것이다.

그러므로 나의 두 번째 결론은, 악은 궁극적이고 비범한 극단으로 수행된 게으름(laziness carried to its ultimate, extraordinary extreme)이라는 것이다. 정의했듯이 사랑은 게으름의 반대말(antithesis)이다. 평범한 게으름은 사랑하는 데 수동적으로 실패하는 것이다. 어떤 평범하게 게으른 사람들은 강요받지 않는 한 자신을 확장하기 위해 손가락 하나 까딱하지 않을 수 있다. 그들의 존재는 사랑 없음(no love)의 발현이지만, 그들은 악하지 않다. 반면에 진정으로 악한 사람들은 자신을 확장하는 것을 수동적이 아니라 능동적으로 피한다. 그들은 자신의 게으름을 보호하기 위해, 병든 자아의 온전함(integrity)을 보존하기 위해 자신들의 권력 안에 있는 어떤 행동이라도 취할 것이다. 타인을 양육하기보다는 이 대의를 위해 실제로 타인을 파괴할 것이다. 필요하다면 자신의 영적 성장의 고통을 피하기 위해 살인까지도 할 것이다. 병든 자아의 온전함이 주변 사람들의 영적 건강에 의해 위협받으므로, 그들은 온갖 수단을 동원하여 자신들 근처에 존재할지 모르는 영적 건강을 짓부수고 허물어뜨리려 할 것이다. 그러므로 나는 악을, 영적 성장을 양육할 목적으로 자아를 확장하는 것을 피하기 위해 정치적 권력을 행사하는 것—즉, 명시적 또는 암묵적 강압에 의해 타인에게 자신의 의지를 강요하는 것—으로 정의한다. 평범한 게으름은 사랑 없음(no love)이고, 악은 반(反)사랑(antilove)이다.

나의 세 번째 결론은, 적어도 인간 진화의 이 단계에서 악의 존재는 불가피하다는 것이다. 엔트로피의 힘과 인간이 자유 의지를 소유한다는 사실을 감안할 때, 게으름이 어떤 이들에게서는 잘 억제되고 다른 이들에게서는 완전히 억제되지 않는 것은 불가피하다. 한편으로는 엔트로피, 다른 한편으로는 사랑의 진화적 흐름이 대립하는 힘이므로, 이 힘들이 대부분의 사람에게서 비교적 균형을 이루는 반면, 한쪽 극단의 소수는 거의 순수한 사랑을, 다른 쪽 극단의 소수는 순수한 엔트로피 또는 악을 발현하는 것은 자연스러운 일이다. 그것들이 충돌하는 힘이므로, 극단에 있는 자들이 전투에 갇히게 되는 것 또한 불가피하다. 선이 악을 미워하는 것만큼이나 악이 선을 미워하는 것은 자연스럽다.

마지막으로, 나는 엔트로피가 거대한 힘이지만, 인간 악이라는 가장 극단적인 형태에서는 사회적 힘으로서 이상하게도 비효율적이라는 결론에 도달했다. 나 자신도 악이 행동하여 수십 명의 아이들의 영혼과 마음을 악랄하게 공격하고 효과적으로 파괴하는 것을 목격했다. 하지만 악은 인간 진화의 큰 그림에서 역효과를 낳는다. 그것이 파괴하는 모든 영혼에 대해—그리고 많다—타인의 구원에 도구가 된다. 부지불식간에 악은 타인들에게 자신의 얕은 여울(shoals)에서 멀어지라고 경고하는 등대 역할을 한다. 우리 대부분은 악의 터무니없음에 대해 거의 본능적인 공포감을 은혜로 받았기에, 악의 존재를 알아볼(recognize) 때 우리 자신의 인격은 그 존재에 대한 자각으로 연마된다. 악에 대한 우리의 의식은 우리 자신을 정화하라는 신호다. 예를 들어 그리스도를 십자가에 올린 것은 악이었고, 그로써 우리가 멀리서 그분을 볼 수 있게 했다. 세상의 악에 맞서는 싸움에 개인적으로 참여하는 것은 우리가 성장하는 방법 중 하나다.
